### ISSUE TITLE
Please read if changing path to STL files

### ISSUE THREAD

**Issue by davidhoness** [raspberrypilearning/astro-pi-flight-case#9]
There is a short URL (http://rpf.io/apstl) pointing to the STL folder which is featured in the Astro Pi 3D printed assembly [video](https://www.youtube.com/watch?v=zmJOA6WzfZw).

![apstl](https://user-images.githubusercontent.com/6640424/29063601-507e1318-7c1e-11e7-9c70-0f534a8d41d6.jpg)

If the path to the 3D print STL files is ever changed can the short URL be updated in http://rpf.io/admin/ please? I have updated it on 08/08/17.

Many thanks

**Comment by lawsie** [comment]
@MarcScott

**Comment by MarcScott** [comment]
Noted
